= Disposition for Data Management Handbook
:sectnums:

This documents shows the structure of the Data Management Handbook.

Current status: The haders from V1 of DMH has been added to this document. 
Numbering of chapters is from this first version of the document.

Todo:

* Extract and rewrite the generic parts
* Create templates for partner specific parts (usually the "implementation" header), suggested sub- sections:
** Background (only if needed!)
** Current implementation (should include subsections or links to how-to documents)
** Planned developements (if any)
* Add the information from the Quick guide

[[introduction]]
== Introduction

General part

* Background 1.1: MET/ Partner specific
** Data at MET Norway 1.1.1: MET/ Partner specific
** MET Norway’s position​ 1.1.2: MET/ Partner specific
** MET Norway’s data users​ 1.1.3: Most of this is General related and should be moved elsewhere
​** External data management requirements and forcing mechanisms 1.1.4: General, should be moved up in this section
​*​ 1.2 Principles for data management at MET Norway: Mostly generic, some history/background and some (small) METspecific parts
**​ 1.2.1 Our data management model: More general?
***​ 1.2.1.1 Dataset: MET specific
***​ 1.2.1.2 Metadata: Generic, MET specific can be extracted at the end. (and add the new stuff from S-ENDA project)
**​ 1.2.2 Human roles in data management: Generic
​***​ 1.2.2.1 Data Consumer: Generic
​***​ 1.2.2.2 Data Provider: Generic
​***​ 1.2.2.3 Data Management Roles: Generic
​**​ 1.2.3 Summary of data management requirements (ADC model): MET specific, "how tos" should be added or linked

== Structuring and Documenting Data for Efficient Discovery and Use
=======
[[background]]
===​ Background

MET/ Partner specific

​===​= 1.1.1 Data at MET Norway

MET/ Partner specific

​====​ 1.1.2 MET Norway’s position

MET/ Partner specific

​====​ 1.1.3 MET Norway’s data users

Most of this is General related and should be moved elsewhere
​
====​ 1.1.4 External data management requirements and forcing mechanisms

General, should be moved up in this section
​
===​ 1.2 Principles for data management at MET Norway

Mostly generic, some history/background and some (small) METspecific parts

​====​ 1.2.1 Our data management model

More general?

​=====​ 1.2.1.1 Dataset

MET specific

====​=​ 1.2.1.2 Metadata

Generic, MET specific can be extracted at the end. (and add the new stuff from S-ENDA project)

​====​ 1.2.2 Human roles in data management

Generic
​
=====​ 1.2.2.1 Data Consumer

Generic
​
=====​ 1.2.2.2 Data Provider

Generic
​
=====​ 1.2.2.3 Data Management Roles

Generic
​
====​ 1.2.3 Summary of data management requirements (ADC model)

MET specific, "how tos" should be added or linked

==​ 2 Structuring and Documenting Data for Efficient Discovery and Use

​
===​ 2.1 Purpose

General, and can probably be added directly
​
=== 2.2 Implementation

General
​
====​ 2.2.1 Current practice in structuring and documenting data

Can make a general list, and add section with in house data formats

​====​ 2.2.2 Current implementation of Arctic Data centre model

Can make a general list, and add section with in house data formats

​====​ 2.2.3 Planned developments in the near-term (< 2 years)

MET specific, needs to be updated with current status

​====​ 2.2.4 Expected evolution in the longer term (> 2 years)

MET specific, needs to be updated with current status

​==​ 3 Data Services
​
=== 3.1 Purpose

Generic

​=== 3.2 Implementation

MET specific, needs to add information about the metadata storage and mms

​====​ 3.2.1 Legacy data organisation

MET specific, needs to add information about the metadata storage and mms

​====​ 3.2.2 Evolution of the current implementation

MET specific, needs to add information about the metadata storage and mms

​====​ 3.2.3 Current implementation of Arctic Data Centre model

MET specific, needs to add information about the metadata storage and mms

​==== 3.2.4​ Planned developments in near-term (< 2 years)

MET specific, needs to add information about the metadata storage and mms

​==== 3.2.5​ Expected evolution in the longer term (> 2 years)

MET specific, needs to add information about the metadata storage and mms
Some Generic parts that needs to be extracted and perhaps put in another place

​== ​4 User Portals and Documentation

​=== 4.1​ Purpose

Generic

===​ 4.2​ Implementation of the MET portal

Met specific

​==== 4.2.1​ Current implementation of MET portal

MET specific

​==== 4.2.2​ Planned developments in near-term (< 2 years)

MET specific 

​=== 4.3​ Implementation of targeted portals

MET specific

​==== 4.3.1​ Current implementation of targeted portals in Arctic Data Centre model

MET specific

​==== 4.3.2​ Planned developments in near-term (< 2 years)

MET specific

​==== 4.3.3​ Expected evolution in the longer term (> 2 years)

MET specific

​== 5​ Data Governance

Generic 

​=== 5.1​ Purpose

Generic

​=== 5.2​ Background

MET Specific

​=== 5.3​ Organisational Roles

Currently no content

​=== 5.4​ Data life cycle management

Generic 

​==== 5.4.1​ MET Norway’s internal production chains

Met specific

​==== 5.4.2​ Data Management Plan

Generic
needs to be updated and MET/partner specific DMPs needs a location in the document

​=== 5.5​ Implementation plan

Chapter 5.5 and all subchapters are very MET specific, alternatively DMH specific. Should be rewritten and perhaps placed differently
​
==== 5.5.1​ Current implementation
​
==== 5.5.2​ Planned developments in near-term (< 2 years)
​
==== 5.5.3​ Expected evolution in the longer term (> 2 years)

​== 6 Use cases and workflow checklists
​
=== 6.1 Purpose

General, Use cases are MET specific. Need to figure out what to do with the workflow checklist

​=== 6.2 Use Case descriptions
​
====​ 6.2.1 UC1: A new NWP model is introduced and the data it produces shall be made available to the consumers.
​
====​ 6.2.2 UC2: A new operational in situ observation source is introduced and its data shall be made freely available to public consumers after QC.
​
====​ 6.2.3 UC3: A researcher has funding from NFR to produce a dedicated set of model experiments.

====​ 6.2.4 UC4: A user shall extract observed and forecasted temperature time series data values over Longyearbyen.
​
====​ 6.2.5 UC5: A new ocean wave model is introduced and the data it produces shall be made available to consumers.

== Acknowledgements

MET specific? or should be added to background?

== References
​
== Glossary of Terms and Names

== ​List of Acronyms

== Appendix A: List of Referenced Software or Services

== Appendix B: Users of MET Norway’s Geodata

