version: '3.4'

services:
  acdd_elements:
    build:
      context: .
      args:
        PY_MMD_TOOLS_VERSION: ${PY_MMD_TOOLS_VERSION:-master}
      dockerfile: Dockerfile.acdd_elements
    volumes:
      - ./doc:/doc
    command: ./yaml2adoc.py -o /doc/acdd-elements.adoc
