version: '3.4'

services:

  html:
    build:
      context: .
      dockerfile: Dockerfile.asciidoctor
    volumes:
      - ./doc:/workdir
      - ./html:/html
    command: >
      asciidoctor -r asciidoctor-diagram
      -a special_intro=${SPECIAL_INTRO:-specialized_intro_template.adoc} 
      -a special_strudoc=${SPECIAL_STRUDOC:-specialized_strudoc_template.adoc}
      -a special_data_services=${SPECIAL_DATA_SERVICES:-specialized_data_services_template.adoc}
      -a special_user_portals=${SPECIAL_USER_PORTALS:-specialized_userportals_template.adoc}
      -a special_data_governance=${SPECIAL_DATA_GOVERNANCE:-specialized_datagov_template.adoc}
      -a special_practical_guidance=${SPECIAL_PRACTICAL_GUIDANCE:-specialized_practical_guidance_template.adoc}
      -a special_appendix_users=${SPECIAL_APPENDIX_USERS:-specialized_appendix_users.adoc}
      -a toc=left
      -n /workdir/data-management-handbook.adoc 
      -D /html

  pdf:
    build:
      context: .
      dockerfile: Dockerfile.asciidoctor
    volumes:
      - ./doc:/workdir
      - ./pdf:/pdf
    command: >
      asciidoctor-pdf -r asciidoctor-diagram
      -a special_intro=${SPECIAL_INTRO:-specialized_intro_template.adoc} 
      -a special_strudoc=${SPECIAL_STRUDOC:-specialized_strudoc_template.adoc}
      -a special_data_services=${SPECIAL_DATA_SERVICES:-specialized_data_services_template.adoc}
      -a special_user_portals=${SPECIAL_USER_PORTALS:-specialized_userportals_template.adoc}
      -a special_data_governance=${SPECIAL_DATA_GOVERNANCE:-specialized_datagov_template.adoc}
      -a special_practical_guidance=${SPECIAL_PRACTICAL_GUIDANCE:-specialized_practical_guidance_template.adoc}
      -a special_appendix_users=${SPECIAL_APPENDIX_USERS:-specialized_appendix_users.adoc}
      -a pdf-themesdir=/workdir
      -a pdf-theme=dmh
      -n /workdir/data-management-handbook.adoc
      -D /pdf
