version: '3.4'

services:
  acdd_elements:
    build:
      context: .
      args:
        PY_MMD_TOOLS_VERSION: ${PY_MMD_TOOLS_VERSION:-master}
      dockerfile: Dockerfile.acdd_elements
    volumes:
      - ./source:/source
    command: yaml2adoc -o /source/acdd-elements.adoc
