version: '3.4'

services:
  acdd_elements:
    build:
      context: .
      args:
        PY_MMD_TOOLS_VERSION: issue158_non_acdd_attrs #${PY_MMD_TOOLS_VERSION:-master}
      dockerfile: Dockerfile.acdd_elements
    volumes:
      - ./source:/source
    command: ./yaml2adoc.py -o /source/acdd-elements.adoc
