#
# Docker file used in GitHub Actions to build HTML and PDF
# versions of metno/data-management-handbook
#

#FROM ruby:alpine
FROM asciidoctor/docker-asciidoctor:latest
LABEL maintainer="mortenwh@met.no"

#RUN gem install asciidoctor; \
#    gem install asciidoctor-pdf --pre; \
#    gem install asciidoctor-diagram

RUN mkdir /workdir; \
    mkdir /pdf; \
    mkdir /html

VOLUME /html
VOLUME /pdf
VOLUME /workdir
WORKDIR /workdir
