[[data-services]]
== Data Services
:xrefstyle: short

The purpose of this chapter is to describe the services existing and to be developed that benefit from the standardisation performed in the previous step. The information structures described in the previous chapter pave the way for efficient data discovery and use through tools and automated services. Implementation of the services must be in line with the institute’s delivery architecture.

This includes:

1. data ingestion, storing the data in the proper locations for long term preservation and sharing;
2. data cataloging, extracting the relevant information for proper discovery of the data;
3. configuration of visualisation and data publication services.

When planning and implementing data services, there are a number of external requirements that constrain choices, especially if reuse of solutions nationally and internationally is intended and wanted for the data in question. At the national level, important constraints are imposed by the national implementation of the <<inspire,INSPIRE>> directive through Norge digitalt. 



 
