[[practical-guides]]
== Practical Guides

This chapter includes how-to's and other practical guidance for data producers.

// add any descriptions and introductions needed, add any subchapters needed below. This chapter should describe what is being done, how it is done and who is doing it.

[[netcdf-cf-guide]]
=== Submitting data as NetCDF-CF

==== Workflow

. Define your dataset (see <<glossary-dataset,Dataset>>)
. Create a NetCDF-CF file (see <<data-as-netcdf-cf>>)

  * Add discovery metadata as global attributes (see <<acdd-elements,global attibutes section>>)
  * Add variables and <<glossary-use-metadata,use metadata>> following the link:https://cfconventions.org/[CF conventions]

. Store the NetCDF-CF file in a suitable location, and distribute it via thredds or another dap server (see, e.g., <<add-to-thredds>>)
. Register your dataset in a searchable catalog (see <<register-dataset-in-catalog>>)

  * Test that your dataset contains the necessary discovery metadata and create an MMD xml file (see <<local-mmd-xml-generation>>)
  * Test the MMD xml file (see <<test-mmd-file>>)
  * Push the MMD xml file to the discovery metadata catalog (see <<push-mmd-file>>)

:numbered:
include::acdd-elements.adoc[]

:numbered:
include::register_context.adoc[]

:numbered:
include::search_context.adoc[]

// optional subchapter that can be used as a checklist for data managers.
