[[practical-guides]]
== Practical Guides

This chapter includes how-to's and other practical guidance for data producers.

// add any descriptions and introductions needed, add any subchapters needed below. This chapter should describe what is being done, how it is done and who is doing it.

[[netcdf-cf-guide]]
=== NetCDF-CF datasets

==== Workflow

. Define your dataset (see <<glossary-dataset,Dataset>>)
. Create a netCDF-CF file (see, e.g., link:https://unidata.github.io/netcdf4-python/[netCDF4-python docs], or link:http://xarray.pydata.org/en/stable/user-guide/io.html[xarray docs])

  * Add discovery metadata as global attributes (see <<acdd-elements,global attibutes section>>)
  * Add variables and <<glossary-use-metadata,use metadata>> following the link:https://cfconventions.org/[CF conventions]

. Store the file in a suitable location, and distribute it via thredds or another dap server (see, e.g., <<add-to-thredds>>)
. Test that your dataset contains the necessary discovery metadata and create MMD xml file(s) (see <<test-and-create-mmd-file>>)
. Index your data in a searchable metadata catalog under a development environment
. Verify that the development CSW service works as expected (e.g., that it provides correct metadata)
. Index your data in a staging/production environment

The data producer should be able to handle points 1-4, whereas the last four points (5-7) should be done with help from a system expert.

:numbered:
include::acdd-elements.adoc[]

:numbered:
include::register_context.adoc[]

:numbered:
include::search_context.adoc[]

// optional subchapter that can be used as a checklist for data managers.
