[[search_context]]
=== Search context

==== Using OpenSearch

===== Local test machines

The `localtest` and `localdev` virtual machines provide OpenSearch support through link:https://github.com/geopython/pycsw[PyCSW]. To test OpenSearch via the browser, start the `localtest` vm (`vagrant up localtest`) and go to the following address:

* `http://10.20.30.10/pycsw/csw.py?mode=opensearch&service=CSW&version=2.0.2&request=GetCapabilities`

This will return a description document of the catalog service. The `URL` field in the description document is a template format that can be used to represent a parameterized form of the search. The search client will process the URL template and attempt to replace each instance of a template parameter, generally represented in the form {name}, with a value determined at query time (link:https://github.com/dewitt/opensearch/blob/master/opensearch-1-1-draft-6.md#opensearch-url-template-syntax[OpenSearch URL template syntax]). The question mark following any search parameter means that the parameter is optional.

===== on the online catalog

For searching the online metadata catalog, please refer to `https://csw.s-enda.k8s.met.no/` instead of `http://10.20.30.10/`.

===== OpenSearch examples

To find all datasets in the catalog:

* `https://csw.s-enda.k8s.met.no/?mode=opensearch&service=CSW&version=2.0.2&request=GetRecords&elementsetname=full&typenames=csw:Record&resulttype=results`

Or datasets within a given time span:

* `http://10.20.30.10/?mode=opensearch&service=CSW&version=2.0.2&request=GetRecords&elementsetname=full&typenames=csw:Record&resulttype=results&time=2000-01-01/2020-09-01`

[note]
====
pyCSW opensearch time queries do not relate to the "expected" `start_date` and `end_date` MMD fields, or the associated `beginPosition` and `endPosition`, in the pyCSW ISO19139 profile. We are working to understand and handle this...
====

Or datasets within a geographical domain (defined as a box with parameters min_longitude, min_latitude, max_longitude, max_latitude):

* `http://10.20.30.10/?mode=opensearch&service=CSW&version=2.0.2&request=GetRecords&elementsetname=full&typenames=csw:Record&resulttype=results&bbox=0,40,10,60`

Or, datasets from any of the Sentinel satellites:

* `http://10.20.30.10/?mode=opensearch&service=CSW&version=2.0.2&request=GetRecords&elementsetname=full&typenames=csw:Record&resulttype=results&q=sentinel>`_`

==== Using web portals

*GeoNorge.no*

*TODO:* describe how to search in geonorge, possibly with screenshots

==== Using QGIS

The production server for the CSW catalog service is available at link:https://csw.s-enda.k8s.met.no. This can be used from QGIS, as follows:

. Select `Web > MetaSearch > MetaSearch` menu item
. Select `Services > New`
. Type, e.g., `csw-senda` for the name
. Type `https://csw.s-enda.k8s.met.no` for the URL

Under the `Search` tab, you can then add search parameters, click `Search`, and get a list of available datasets.






