[[specialized-struct-and-doc]]
=== Structuring and documenting data at METNorway

[[Current-practice]]
==== Current practice in structuring and documenting data

The dynamical geodata at MET Norway can be either <<gridded-data,gridded data>> or <<non-gridded-data,non-gridded data>>.

.Data types available at METNorway, with the fileformats supported. The primary fileformat is marked in *bold*
[[tabl-localdatatypes]]
[%header, cols=4*a]
|===
|Supported file formats/structures
|Datatype
|Available metadata
|Examples
|Comments

|*<<netcdf-cf,NetCDF/CF>>*
|<<gridded-data,Gridded data>>
|<<use-metadata,use metadata>>, <<discovery-metadata,discovery>> metadata for <<adc,ADC>>-based projects
|Numerical model output, satellite derived datasets
|

|
|
|
|
|
|===

<<dynamic-geodata,Dynamic geodata>> can be categorized into the following two types based on the structure of the data:

//Do we have a good description of these two types? These descriptions are from https://www.ssec.wisc.edu/mcidas/doc/prog_man/2015/access-3.html and https://www.ssec.wisc.edu/mcidas/doc/prog_man/2015/access-4.html

[[gridded-data]]*Gridded data:* Grids may contain any data that can be represented in a two-dimensional matrix.  

[[non-gridded-data]]*Non-gridded data:* Typically point data, data occuring at irregularly spaces location on the Earth or vertically. Can contain mixed data types.
 
*Gridded data* include numerical model output, many satellite-derived datasets. The institute has already committed to employing NetCDF/CF as the primary method for structuring gridded data and the implementation is largely complete, although CF-compliance is not enforced for all data files. For documentation, CF-compliance ensures the availability of adequate use metadata in each file. Discovery metadata are not as well-implemented at present. In some cases (e.g. in ADC-based projects, see Section 2.2.2) they are provided by applying compliance to the ACDD convention in structuring the NetCDF files, in others through manual processes; in still others, no discovery metadata are produced at all.
 
WMO membership obliges the institute to provide and handle GRIB files; this is done for several datasets, but GRIB does not provide use or discovery metadata in itself. 
Non-gridded data include most observational data like observations at weather stations, radiosondes, CTD profiles in the ocean, etc. These diverse data types are maintained in many different solutions, ranging from files (e.g. weather station observations extracted from WMO GTS in WMO BUFR format and subsequently converted to NetCDF/CF for easier usage) or DBMS solutions (e.g., the institute’s weather station climate data storage). Software (frost2nc) for conversion  output from the climate data storage to NetCDF/CF for user consumption is developed and implemented for some stations. The CF convention has standardised encoding plans (featureType) for time series at stations (e.g., weather stations), profiles (e.g., CTD stations and radiosondes) and trajectories; an encoding standard for geometries (e.g., shapes) is under development. Discovery metadata can be extracted from the DBMS insofar as they are available; selection and extraction of the metadata must be configured manually for each dataset. Currently, a new DBMS is being designed and expected to enter into service in 2019. 
The WMO standard for observations is BUFR, which is also supported but is not self-describing. The institute also maintains other types of data, like textual representations of the weather forecast. Most of these are currently not in any standard format, a notable exception being newly available warnings in CAP format, which is a WMO/OASIS standard format.


==== Current implementation of Arctic Data centre model
As noted above, MET Norway has already decided to use NetCDF/CF as the primary file format. It is a self describing format which simplifies the sharing of data externally and is easy to link with standard data sharing protocols like OGC WMS and OpeNDAP. NetCDF/CF specifies a standardised annotation of the content in the form of CF standard_name attribute for variables which is compliant with semantic web approaches. standard_name cannot cover all conceivable parameters and there is a governance structure for CF that approves new entries, albeit slowly (order of three months). However, the current practice at the institute does not cover generation of discovery metadata.
Currently, discovery metadata are encoded according to the MMD standard [RD8]. This is an in-house specification required to be compatible with ISO 19115 and GCMD DIF, which are the most-used discovery metadata standards within geoscience. A feature of the MMD specification is that configuration metadata can be included with the discovery metadata. The compliance requirement implies that the relevant information from GCMD DIF and ISO 19115 should be transferred into MMD, but that not all information in MMD necessarily have a place in ISO 19115 or GCMD DIF. MMD records are versioned using a Subversion repository. 
In externally funded ADC-related projects, support for automatic generation of MMD records from NetCDF/CF files containing global attributes according to the Attribute Convention for Dataset Discovery (ACDD [RD5]) has been developed. 
WMO and regional (e.g. INSPIRE) and national (e.g. Norway Digital) data sharing services all rely on ISO 19115 as the discovery metadata structure. A weakness of many of the top level data sharing efforts is lack of controlled vocabularies and ontologies for use in free text fields, which can lead to unusable content entries. Implementation of the standard_name attribute in NetCDF/CF is one effort to fill this need; another is ACDD, which explicitly requires keywords and vocabulary references as NetCDF attributes.
We have some activity on ingestion of in situ observational data from KDVH/ObsklimDL in the form of NetCDF/CF, combined with services providing necessary site metadata.
​
==== Planned developments in the near-term (< 2 years)

// add a description of the short-term planned developements for your institution

The community focus on standardised data documentation and utilisation of <<controlled-vocabulary,controlled vocabularies>> (initially) and <<ontology,ontologies>> (in the longer term) is gaining momentum. In the short term a better overview and coordination between various efforts is expected. This is, however, primarily done by the technical community today and lacks support and understanding in the science community, although this is increasing.

Nationally, Norway was very late establishing a national service for issuing globally unique and persistent identifiers (<<pid,PID>>) for <<dataset,datasets>>. This service was established in 2017 for Norway and is now a crucial element of proper data documentation and encoding. Use of <<pid,PID>>s is required to establish good services around the data. Currently, MET Norway, together with many other institutions, is using Universally Unique Identifiers (<<uuid,UUID>>) which are generated and managed locally. This will be fully implemented within the next 2 years along with full support for <<doi,DOI>>s where needed. 

At MET Norway, we will work to extend our metadata standards with information on the software used in production and processing, for example numerical model configuration, satellite data processing software, etc. We will follow emerging international standards, if available. This is a step in improving <<data-provenance,provenance>> information on the <<dataset,datasets>>.

==== Expected evolution in the longer term (> 2 years)

// add a description of the long-term planned developements for your institution

//missing section link

In the longer term, we expect much more coordinated and dedicated efforts to develop controlled <<vocabulary,vocabularies>> and <<ontology,ontologies>> through non-technical involvement. These efforts will have a shorter way into <<semantic-web,semantic> services which can be integrated in the <<data-management,data management>> systems and support interdisciplinary usage. There is also a strong focus on methodologies for <<data-provenance,data provenance>>. The <<prov,PROV>> standard and tools around it are under development through <<eosc,EOSC>> and <<envir-fair,ENVRI-FAIR>> and are expected to reach a relevant readiness level within 2-3 years (see also Section 3.2.5). 
Services utilising <<pid,PID>>s will increase in the coming years and are crucial to ensure proper tracking of data through the value chain to decisions. <<pid,PID>>s can also be attributed to software, publications, hardware, personnel, etc. 
