[[human-roles]]
=== Human roles in data management

[[human-roles-context]]
==== Context

Data is processed and interpreted to generate knowledge (e.g., about the weather) for end users. The knowledge can be presented as information in the form of actual data, illustrations, text or other forms of communication. In this context, an illustration is a representation of data, whereas data means the numerical values needed to analyse and interpret a natural process (i.e., calibrated or with calibration information; it must be possible to understand the meaning of the numerical value from the available and machine-readable information).

[plantuml, information-to-knowledge, png]
....
state "Knowledge generation" as kg {
state Data {
  Data : Mercury pressure
  Data : Wind speed and direction
}

state "Processing and interpretation" as PI {
  PI : Temperature changes
  PI : Wind changes
}

state Knowledge {
  Knowledge :  It will most likely be raining
}

}

Data --> PI
PI --> Knowledge
Knowledge --> Data : Trace and verify
....

*Definition:*
[DEFINITION]
====
Data here means the numerical values needed to analyse and interpret a natural process (i.e., calibrated or with calibration information, provenance, etc.; it must be possible to understand the meaning of the numerical value from the available and machine-readable information).
====

Advanced users typically consume some type of data in order to process and interpret it, and produce new knowledge, e.g., in the form of a new dataset or other information. The datasets can be organised in different levels, such as the link:http://codes.wmo.int/wmdr/_SourceOfObservation[WMO WIGOS definition for levels of data]. Less advanced users apply information based on data (e.g., an illustration) to make decisions (e.g., clothing adapted to the forecast weather).

[[user-definitions]]
==== User definitions

We define two types of users:

1. *Producers*: Those that create / produce data
2. *Consumers*: Those that consume data

A consumer of one level of data is typically a producer of data at the next level. A user can both consume data and produce data, or just have one of these roles (e.g., at the start/end of the production chain).

[plantuml, user-definitions, png]
....
package "Level 0 data" as L0 {
  (Consume data) as (CD0)
}

package "Level 1 data" as L1 {
  (Produce data) as (PD1)
  (Consume data) as (CD1)
}

actor "L0 consumer / L1 producer" as L0C
actor "L1 consumer" as L1C

L0C --> (CD0)
L0C --> (PD1)
L1C --> (CD1)
....

[[data-consumer]]
===== Data consumers

We split between three types of data consumers: (1) advanced, (2) intermediate, and (3) simple. These are defined below.

[[advanced-consumers]]
====== Advanced consumers

Advanced consumers require information in the form of data and metadata (including provenance) to gain a full understanding of what data exists and how to use it (discovery and use metadata), and to automatize the generation of derived data (new knowledge generation), verification (of information), and validation of data products.

Example questions:

* Need all historical weather data, that can be used to model / predict the weather in the future

Specific consumers:

* Researcher (e.g., for climate projections within the "Klima i Norge 2100" research project)

[[intermediate-consumers]]
====== Intermediate consumers

Intermediate consumers need enough information to find data and understand if it can answer their question(s) (discovery and use metadata). Also, they often want to cross reference a dataset with another dataset or metadata for inter-comparative verification of information.

Example questions:

* Is this observation a record / weather extreme (coldest, warmest, wettest)?
* What was the amount of rain in last month in a certain watershed?

Specific consumers:

* Klimavakt (MET)
* Developer (app, website, control systems, machine learning, etc.)
* Energy sector (hydro, energy prices)
* External partners


[[simple-consumers]]
====== Simple consumers

Simple consumers do not have any prior knowledge about the data. Information in the form of text or illustrations is sufficient for their decision making. They do not need to understand either data or metadata, and they are most likely looking for answers to simple questions.

Example questions:

* Will it be raining today?
* Can the event take place, or will the weather impeed it?
* When should I harvest my crops?

Specific consumers:

* Event organizer
* Journalist
* Farmer, or other people who work with the land like tree planters

[NOTE]
====
An advanced consumer may discover information pertaining a role as a simple consumer. Such a user may, for some reason, be interested in tracking the data in order to use it together with other data (interoperability) or to verify the information. Therefore, it is important to have provenance metadata pointing to the basic data source(s) also at the simplest information level.
====

[[data-producers]]
===== Data producers

A producer is an advanced consumer at one level of data that generate new information at a higher level. This new information could be in the form of actual data or simple information, such as an illustration or a text summary. It is essential that any information can be traced back to the source(s).

[[data-management-roles]]
===== Data Management Roles

Between the data providers and data consumers are the processes that manage and deliver the datasets (cf. <<img-value-chain>>). A number of human roles may be defined with responsibilities that, together, ensure that these processes are carried out in accordance with the data management requirements of the organisation. The definition and filling of these roles depend heavily on the particular organisation, and each organisation must devise its own best solution. 
