[[introduction]]
== Introduction
:xrefstyle: short

//not updated: chapter links, check all links to glossary and acronyms

The purpose of the Data Management Handbook (<<dmh,DMH>>) is threefold:

. to provide an overview of the principles for data management to be employed;
. to help personnel identify their roles and responsibilities for good data management; and
. to provide personnel with practical guidelines for carrying out good data management.

<<glossary-data-management,_Data management_>> is the term used to describe the
handling of data in a systematic and cost-effective manner. The data management
regime should be continuously evolving, to reflect the evolving nature of data
collection. Therefore, this <<dmh,DMH>> is a living document that will be
revised and updated from time to time in order to maintain its relevance.

The <<dmh,DMH>> is a strategic governing document and should be used as part of
the quality framework the organisation is using. 

// Remember to add links/references to the chapters below

The primary focus of this <<dmh,DMH>> is on the management of
<<glossary-dynamic-geodata, dynamic geodata>>. <<glossary-dynamic-geodata,
Dynamic geodata>> is weather, environment and climate-related data that changes
in space and time and is thus descriptive of processes in nature. Examples are
weather observations, weather forecasts, pollution (environmental toxins) in
water, air and sea, information on the drift of cod eggs and salmon lice, water
flow in rivers, driving conditions on the roads and the distribution of sea
ice. <<glossary-dynamic-geodata, Dynamic geodata>> provides important
constraints for many decision-making processes and activities in society.

The intended audience for this DMH is any personnel involved in the process of
making data available to the end user. This process can be viewed as a value
chain that moves from the producer of the data to the data consumer (i.e., the
end user). The process is further described in <<value-chain>>
(<<img-value-chain>>).  

The handbook can be used in three ways: 

. Read <<PrinciplesDataManagement>> to get an overview of the main principles and structural organisation of the <<glossary-data-management,data management>>;
. Read Chapters <<structuring-and-documenting>>-<<data-governance>> to learn about how <<glossary-data-management,data management>> is currently implemented, and how it is expected to evolve in the next few years; and
. Read <<practical-guides>> to find how-to's and practical guidelines for defining, documenting and making your data available, as well as how to search and access data through APIs.

[NOTE]
====
If you do not think that your data fits into the Data Management Model described here, please contact the <<met-org-roles,Data Management Group>>. We have several examples of data that is not available in, e.g., NetCDF-CF that have been added to the catalog, and it is usually possible to find pragmatic solutions to FAIRifying data.
====
