[[practical-guides]]
== Practical Guides

This chapter includes how-to's and other practical guidance for data producers.

// add any descriptions and introductions needed, add any subchapters needed below. This chapter should describe what is being done, how it is done and who is doing it.

[[dmp-guide]]
=== Create a Data Management Plan (DMP)

The funding agency of your project will usually provide requirements, guidelines or a template for the DMP. If this is not the case or for datasets that are not part of a project use the template provided by your institution or the template based on the link:https://www.forskningsradet.no/contentassets/e4cd6d2c23cf49d4989bb10c5eea087a/se_rdm_practical_guide_final.pdf[recommendations by Science Europe].

==== Using easyDMP

. Log in to link:https://easydmp.sigma2.no/login/[easyDMP], use *Dataporten* if your institution supports that, otherwise pick one of the other login methods.
. Click on *+ Create a new plan* and pick a template
. By using the *Summary* button from page two and on, you can get an overview of all the questions.


==== Publishing the plan

Currently you can use the _export_ function in easyDMP to download an HTML or PDF version of the DMP and use it further.
This might change if "link:https://github.com/hmpf/easydmp/issues/226[Hosted DMP]" gets implemented.

[[netcdf-cf-guide]]
=== Submitting data as NetCDF-CF

==== Workflow

. Define your dataset (see <<glossary-dataset,dataset>> and <<dataset>>)
. Create a NetCDF-CF file (see <<data-as-netcdf-cf>>)

  * Add discovery metadata as global attributes (see <<acdd-elements,global attibutes section>>)
  * Add variables and <<glossary-use-metadata,use metadata>> following the link:https://cfconventions.org/[CF conventions]

. Store the NetCDF-CF file in a suitable location, and distribute it via thredds or another dap server (see, e.g., <<add-to-thredds>>)
. Register your dataset in a searchable catalog (see <<register-dataset-in-catalog>>)

  * Test that your dataset contains the necessary discovery metadata and create an MMD xml file (see <<local-mmd-xml-generation>>)
  * Test the MMD xml file (see <<test-mmd-file>>)
  * Push the MMD xml file to the discovery metadata catalog (see <<push-mmd-file>>)

:numbered:
include::acdd-elements.adoc[]

:numbered:
include::register_context.adoc[]

:numbered:
include::search_context.adoc[]

// optional subchapter that can be used as a checklist for data managers.
