[[add-to-thredds]]
==== How to add NetCDF-CF data to thredds

:numbered:
include::{special_nc2thredds}[]

[[register-dataset-in-catalog]]
==== How to register your data in the catalog service

In order to make a dataset findable, a dataset must be registered in a searchable catalog with appropriate metadata. The (meta)data catalog is indexed and exposed through link:https://en.wikipedia.org/wiki/Catalogue_Service_for_the_Web[CSW].

The following needs to be done:

. Generate an MMD xml file from your NetCDF-CF file (see <<local-mmd-xml-generation>>)
. Test your mmd xml metadata file (see <<test-mmd-file>>)
. Push the MMD xml file to the discovery metadata catalog (see <<push-mmd-file>>)

[[local-mmd-xml-generation]]
===== Generation of MMD xml file from NetCDF-CF

Clone the link:https://github.com/metno/py-mmd-tools.git[py-mmd-tools] repo and make a local installation with eg `pip install .`. This should bring in all needed dependencies (we recommend to use a virtual environment).

Then, generate your mmd xml file as follows:

[source]
----
cd script
./nc2mmd.py -i <your netcdf file> -o <your xml output directory>
----

See `./nc2mmd.py --help` for documentation and extra options.

You will find Extensible Stylesheet Language Transformations (XSLT) documents in the link:https://github.com/metno/mmd.git[MMD] repository. These can be used to translate the metadata documents from MMD to other vocabularies, such as ISO19115:

[source]
----
./bin/convert_from_mmd -i <your mmd xml file> -f iso -o <your iso output file name>
----

[[NOTE]]
====
Note that the discovery metadata catalog ingestion tool will take care of translations from MMD, so you don't need to worry about that unless you have special interest in it.
====

[[test-mmd-file]]
===== Test the MMD xml file

Install the link:https://github.com/metno/discovery-metadata-catalog-ingestor[dmci app], and run the usage example locally. This will return an error message if anything is wrong with your MMD file.

You can also test your MMD file via the DMCI API:

[source]
----
curl --data-binary "@<PATH_TO_MMD_FILE>" https://dmci.s-enda-*.k8s.met.no/v1/validate
----

[[push-mmd-file]]
===== Push the MMD xml file to the discovery metadata catalog

For development and verification purposes:

[source]
----
curl --data-binary "@<PATH_TO_MMD_FILE>" https://dmci.s-enda-*.k8s.met.no/v1/insert
----

where `*` should be either dev or staging.

For production (the official catalog):

[source]
----
curl --data-binary "@<PATH_TO_MMD_FILE>" https://dmci.s-enda.k8s.met.no/v1/insert
----

[[test-mmd-ingested]]
===== Check that the MMD file has been added to csw

There are several ways to check if your MMD file has been added to the metadata catalog(s). One way is via regular csw/opensearch requests as described in <<search_context>>, and the examples below.

In addition, a new dataset should get a landing page when it is added. At MET Norway, you can access that as follows:

* `https://data.met.no/dataset/UUID`
* `https://data-staging.met.no/dataset/UUID` (for the staging environment)
* `https://data-test.met.no/dataset/UUID` (for the development environment)

where UUID should be replaced by your dataset uuid (not `no.met:UUID`). Others ways to check are:

* Find the datasets containing `arctic` keyword in the title and on a given date: `https://csw.s-enda*.k8s.met.no/?mode=opensearch&service=CSW&version=2.0.2&request=GetRecords&elementsetname=full&typenames=csw:Record&resulttype=results&q=arctic&time=2023-03-25`
* Find the datasets having a given `metadata_identifier`: `https://csw.s-enda*.k8s.met.no/csw?service=CSW&version=2.0.2&request=GetRecordById&oxml&outputSchema=http://www.isotc211.org/2005/gmd&elementsetname=full&id=no.met:4a34334b-b384-48b3-b846-76807bc006`
* Find the datasets containing `direct` keyword in the title and within a given time span: `https://csw.s-enda*.k8s.met.no/?mode=opensearch&service=CSW&version=2.0.2&request=GetRecords&elementsetname=full&typenames=csw:Record&resulttype=results&q=direct&time=2022-03-01/2022-09-25`
* Or from the command line: `curl "https://csw.s-enda-dev.k8s.met.no/csw?service=CSW&version=2.0.2&request=GetRecordById&oxml&outputSchema=http://www.isotc211.org/2005/gmd&elementsetname=full&id=no.met:4a34334b-b384-48b3-b846-76807bc006ca"`. This means that the dataset ID must be known. Given wrong "id=" in the url, will still give you "200 OK", but the returned xml will only be one line and not a full metadata document.

In all examples, `*` should be omitted to find data in the production environment, or be either "-dev" or "-staging" for the development or staging environments, respectively.

