name: 'html/pdf'

on:
  pull_request: 
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: update source/acdd_elements.adoc
      run: |
        docker-compose -f docker-compose.acdd_elements.yml up

    - name: create html and pdf and update source/acdd-elements.adoc
      run: |
        docker-compose -f docker-compose.asciidoctor.yml up